configmap:
#  db_host: expense-dev.cha660m4gepj.us-east-1.rds.amazonaws.com
  db_host: mysql-dev.raj82s.online
deployment:
  imageURL: 311141550186.dkr.ecr.us-east-1.amazonaws.com/expense/backend
  version: IMAGE_VERSION